services:
  postgres:
      image: postgres:16
      container_name: requests_postgres
      environment:
        POSTGRES_USER: ${DB_USER}
        POSTGRES_PASSWORD: ${DB_PASSWORD}
        POSTGRES_DB: ${DB_NAME}
      restart: unless-stopped
      volumes:
        - postgres_data:/var/lib/postgresql/data
        - ./init.sql:/docker-entrypoint-initdb.d/init.sql:ro,Z
      networks:
        - helpdesk_network
  app:
    build: ../backend
    container_name: requests_app
    expose:
      - "8080"
    restart: unless-stopped
    environment:
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_NAME=${DB_NAME}
      - DB_HOST=${DB_HOST}
      - DB_PORT=${DB_PORT}
    depends_on:
      - postgres
    networks:
      - helpdesk_network
  nginx:
    image: nginx:latest
    container_name: requests_nginx
    ports:
      - "8081:80" 
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro,Z
    depends_on:
      - app
    networks:
      - helpdesk_network
  prometheus:
    image: prom/prometheus
    container_name: prometheus
    restart: unless-stopped
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
    ports:
      - 9090:9090
    volumes:
      - ../monitoring/prometheus.yml:/etc/prometheus/prometheus.yml:ro,Z
      - prometheus_data:/prometheus
    networks:
      - helpdesk_network
  grafana:
    image: grafana/grafana
    container_name: grafana
    restart: unless-stopped
    ports:
      - 3000:3000
    environment:
      - GF_SECURITY_ADMIN_USER=${GRAFANA_USER}
      - GF_SECURITY_ADMIN_PASSWORD=${GRAFANA_PASSWORD}
    volumes:
      - ../monitoring/grafana/datasources:/etc/grafana/provisioning/datasources:ro,Z
      - ../monitoring/grafana/dashboards:/etc/grafana/provisioning/dashboards:ro,Z
      - grafana_storage:/var/lib/grafana
    networks:
      - helpdesk_network
  cadvisor:
    image: gcr.io/cadvisor/cadvisor:v0.52.1
    container_name: cadvisor
    restart: unless-stopped
    privileged: true
    volumes:
      - /:/rootfs:ro
      - /run/user/1000:/run/user/1000:ro
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
      - /etc/machine-id:/etc/machine-id:ro
      - ${DOCKER_STORAGE_PATH:-/var/lib/docker}:/var/lib/containers:ro
    command:
      - '--podman=unix:///run/user/1000/podman/podman.sock'
    networks:
      - helpdesk_network
  node-exporter:
    image: prom/node-exporter:v1.8.1
    container_name: node-exporter
    restart: unless-stopped
    volumes:
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /:/rootfs:ro
    command:
      - '--path.procfs=/host/proc'
      - '--path.rootfs=/rootfs'
      - '--path.sysfs=/host/sys'
      - '--collector.filesystem.mount-points-exclude=^/(sys|proc|dev|host|etc)($|/)'
    networks:
      - helpdesk_network
  postgres-exporter:
    image: prometheuscommunity/postgres-exporter:v0.19.1
    container_name: postgres-exporter
    restart: unless-stopped
    depends_on:
      - postgres
    environment:
      - DATA_SOURCE_NAME=postgresql://${DB_USER}:${DB_PASSWORD}@postgres:5432/${DB_NAME}?sslmode=disable
    networks:
      - helpdesk_network
volumes:
  postgres_data:
  prometheus_data:
  grafana_storage:
networks:
  helpdesk_network:
    driver: bridge