services:
  postgres:
      image: postgres:16
      container_name: requests_postgres
      environment:
        POSTGRES_USER: ${DB_USER}
        POSTGRES_PASSWORD: ${DB_PASSWORD}
        POSTGRES_DB: ${DB_NAME}
      restart: unless-stopped
      volumes:
        - postgres_data:/var/lib/postgresql/data
        - ./init.sql:/docker-entrypoint-initdb.d/init.sql
      networks:
        - helpdesk_network
  app:
    build: ../backend
    container_name: requests_app
    ports:
      - "${APP_PORT}:8080"
    restart: unless-stopped
    volumes:
      - ./.env:/app/.env
    depends_on:
      - postgres
    networks:
      - helpdesk_network
volumes:
  postgres_data:
networks:
  helpdesk_network:
    driver: bridge